import type { BracketSlot } from '../types';

export function generateDoubleElimBracket(tournamentId: string, teamIds: string[]): BracketSlot[] {
  const prefix = `slot_${tournamentId}`;

  const slots: BracketSlot[] = [
    {
      id: `${prefix}_ub_r1_0`,
      round: 'ub_round1',
      label: '胜者组第一轮',
      matchId: null,
      teamAId: teamIds[0] || null,
      teamBId: teamIds[1] || null,
      nextWinSlotId: `${prefix}_ub_final`,
      nextLoseSlotId: `${prefix}_lb_r1`,
      sourceA: 'fixed',
      sourceB: 'fixed',
      sourceSlotAId: null,
      sourceSlotBId: null,
    },
    {
      id: `${prefix}_ub_r1_1`,
      round: 'ub_round1',
      label: '胜者组第一轮',
      matchId: null,
      teamAId: teamIds[2] || null,
      teamBId: teamIds[3] || null,
      nextWinSlotId: `${prefix}_ub_final`,
      nextLoseSlotId: `${prefix}_lb_r1`,
      sourceA: 'fixed',
      sourceB: 'fixed',
      sourceSlotAId: null,
      sourceSlotBId: null,
    },
    {
      id: `${prefix}_ub_final`,
      round: 'ub_final',
      label: '胜者组决赛',
      matchId: null,
      teamAId: null,
      teamBId: null,
      nextWinSlotId: `${prefix}_grand_final`,
      nextLoseSlotId: `${prefix}_lb_final`,
      sourceA: 'winner_of',
      sourceB: 'winner_of',
      sourceSlotAId: `${prefix}_ub_r1_0`,
      sourceSlotBId: `${prefix}_ub_r1_1`,
    },
    {
      id: `${prefix}_lb_r1`,
      round: 'lb_round1',
      label: '败者组第一轮',
      matchId: null,
      teamAId: null,
      teamBId: null,
      nextWinSlotId: `${prefix}_lb_final`,
      nextLoseSlotId: null,
      sourceA: 'loser_of',
      sourceB: 'loser_of',
      sourceSlotAId: `${prefix}_ub_r1_0`,
      sourceSlotBId: `${prefix}_ub_r1_1`,
    },
    {
      id: `${prefix}_lb_final`,
      round: 'lb_final',
      label: '败者组决赛',
      matchId: null,
      teamAId: null,
      teamBId: null,
      nextWinSlotId: `${prefix}_grand_final`,
      nextLoseSlotId: null,
      sourceA: 'loser_of',
      sourceB: 'winner_of',
      sourceSlotAId: `${prefix}_ub_final`,
      sourceSlotBId: `${prefix}_lb_r1`,
    },
    {
      id: `${prefix}_grand_final`,
      round: 'grand_final',
      label: '总决赛',
      matchId: null,
      teamAId: null,
      teamBId: null,
      nextWinSlotId: null,
      nextLoseSlotId: null,
      sourceA: 'winner_of',
      sourceB: 'winner_of',
      sourceSlotAId: `${prefix}_ub_final`,
      sourceSlotBId: `${prefix}_lb_final`,
    },
  ];

  return slots;
}
